spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
